### ISSUE TITLE
Upgrade events

### ISSUE THREAD

**Issue by sschimmel** [lufinkey/react-native-events#5]
The version of events used by react-native-events is version `1.1.1`. That is a three year old version and version `3.0.0` is already out. I'm getting conflicts between packages as the definition of the EventEmitter has changed so the instanceof check returns false.

**Comment by IbrahimCanKALYA** [comment]
I'am facing with this issue to. Version of events  gets a conflict with other versions.

**Comment by lufinkey** [comment]
If you can test and make a PR I'll approve. I'll try to get to updating it though if I can

**Comment by reteps** [comment]
Not sure if that was my issue, but something is messed up:

```
npm ERR! While resolving: beatrunner@0.0.1
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"^0.63.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.41.2" from react-native-events@1.0.15
npm ERR! node_modules/react-native-events
npm ERR!   react-native-events@"^1.0.15" from the root project
```

**Comment by reteps** [comment]
Any ideas what that means?

**Comment by srdadian** [comment]
This is because react-native-events sets the react native dependency version to the old 41 version (and minor upgrades) "^0.41.2", and other packages ask for the last 63 version. It seems like it has not been updated in a while.
If you still want to use this package, you can npm install --legacy-peer-deps which will ignore this dependency issue.

**Comment by lufinkey** [comment]
If someone wants to make a PR I'll approve it, I've just not really been
working on anything with this module in it as of late

**Comment by lufinkey** [comment]
Alright well it's updated. I hope it works, if not just open another issue.
